/* GENERATED BY tools/gen-protocol.mjs FROM shared/protocol.json -- DO NOT EDIT. */

#include "pong_proto.h"
#include <string.h>

/* Little-endian accessors. ARM11 and x86 are both LE, so these compile to
 * plain loads on every target we care about, while staying correct anywhere. */
static inline void wr_u8(uint8_t *p, uint8_t v)   { p[0] = v; }
static inline void wr_u16(uint8_t *p, uint16_t v) { p[0] = (uint8_t)(v); p[1] = (uint8_t)(v >> 8); }
static inline void wr_u32(uint8_t *p, uint32_t v) { p[0] = (uint8_t)(v); p[1] = (uint8_t)(v >> 8); p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24); }
static inline uint8_t  rd_u8(const uint8_t *p)  { return p[0]; }
static inline uint16_t rd_u16(const uint8_t *p) { return (uint16_t)(p[0] | (p[1] << 8)); }
static inline uint32_t rd_u32(const uint8_t *p) { return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24); }

static void wr_header(uint8_t *p, uint8_t type, uint16_t len, uint16_t seq) {
    p[0] = PONG_MAGIC0;
    p[1] = PONG_MAGIC1;
    p[2] = PONG_PROTOCOL_VERSION;
    p[3] = type;
    wr_u16(p + 4, len);
    wr_u16(p + 6, seq);
}

int pong_payload_bytes(uint8_t type) {
    switch (type) {
    case PONG_MSG_HELLO: return 24;
    case PONG_MSG_WELCOME: return 28;
    case PONG_MSG_JOIN: return 8;
    case PONG_MSG_MATCH_START: return 32;
    case PONG_MSG_INPUT: return 12;
    case PONG_MSG_SNAPSHOT: return 24;
    case PONG_MSG_EVENT: return 8;
    case PONG_MSG_PING: return 8;
    case PONG_MSG_PONG: return 12;
    case PONG_MSG_BYE: return 4;
    case PONG_MSG_LEAVE: return 0;
    case PONG_MSG_RESUME: return 20;
    default: return -1;
    }
}

void pong_pad_bytes(uint8_t *dst, size_t dstlen, const char *src) {
    size_t i = 0;
    memset(dst, 0, dstlen);
    if (!src) return;
    for (; i < dstlen && src[i]; i++) dst[i] = (uint8_t)src[i];
}

PongParseResult pong_parse_frame(const uint8_t *buf, size_t len,
                                 PongFrame *out, size_t *consumed) {
    uint16_t plen;
    int expected;
    if (len < PONG_HEADER_BYTES) return PONG_PARSE_NEED_MORE;
    if (buf[0] != PONG_MAGIC0 || buf[1] != PONG_MAGIC1) return PONG_PARSE_BAD_MAGIC;
    if (buf[2] != PONG_PROTOCOL_VERSION) return PONG_PARSE_BAD_VERSION;
    plen = rd_u16(buf + 4);
    if (plen > PONG_MAX_FRAME_BYTES) return PONG_PARSE_BAD_LENGTH;
    expected = pong_payload_bytes(buf[3]);
    if (expected >= 0 && (uint16_t)expected != plen) return PONG_PARSE_BAD_LENGTH;
    if (len < (size_t)PONG_HEADER_BYTES + plen) return PONG_PARSE_NEED_MORE;
    out->type = buf[3];
    out->length = plen;
    out->seq = rd_u16(buf + 6);
    out->payload = buf + PONG_HEADER_BYTES;
    *consumed = (size_t)PONG_HEADER_BYTES + plen;
    return PONG_PARSE_OK;
}

size_t pong_write_hello(uint8_t *out, size_t cap, uint16_t seq, const PongHELLO *m) {
    if (cap < 32) return 0;
    wr_header(out, PONG_MSG_HELLO, 24, seq);
    wr_u8(out + 8, (uint8_t)m->platform);
    wr_u8(out + 9, (uint8_t)m->transport);
    wr_u16(out + 10, (uint16_t)m->caps);
    memcpy(out + 12, m->name, 16);
    wr_u32(out + 28, (uint32_t)m->build_id);
    return 32;
}

bool pong_read_hello(const uint8_t *p, uint16_t len, PongHELLO *out) {
    if (len != 24) return false;
    out->platform = (uint8_t)rd_u8(p + 0);
    out->transport = (uint8_t)rd_u8(p + 1);
    out->caps = (uint16_t)rd_u16(p + 2);
    memcpy(out->name, p + 4, 16);
    out->build_id = (uint32_t)rd_u32(p + 20);
    return true;
}

size_t pong_write_welcome(uint8_t *out, size_t cap, uint16_t seq, const PongWELCOME *m) {
    if (cap < 36) return 0;
    wr_header(out, PONG_MSG_WELCOME, 28, seq);
    memcpy(out + 8, m->session_id, 16);
    wr_u32(out + 24, (uint32_t)m->server_time_ms);
    wr_u16(out + 28, (uint16_t)m->tick_rate);
    wr_u16(out + 30, (uint16_t)m->snapshot_rate);
    wr_u16(out + 32, (uint16_t)m->field_w);
    wr_u16(out + 34, (uint16_t)m->field_h);
    return 36;
}

bool pong_read_welcome(const uint8_t *p, uint16_t len, PongWELCOME *out) {
    if (len != 28) return false;
    memcpy(out->session_id, p + 0, 16);
    out->server_time_ms = (uint32_t)rd_u32(p + 16);
    out->tick_rate = (uint16_t)rd_u16(p + 20);
    out->snapshot_rate = (uint16_t)rd_u16(p + 22);
    out->field_w = (uint16_t)rd_u16(p + 24);
    out->field_h = (uint16_t)rd_u16(p + 26);
    return true;
}

size_t pong_write_join(uint8_t *out, size_t cap, uint16_t seq, const PongJOIN *m) {
    if (cap < 16) return 0;
    wr_header(out, PONG_MSG_JOIN, 8, seq);
    wr_u8(out + 8, (uint8_t)m->mode);
    wr_u8(out + 9, (uint8_t)m->flags);
    memcpy(out + 10, m->room_code, 6);
    return 16;
}

bool pong_read_join(const uint8_t *p, uint16_t len, PongJOIN *out) {
    if (len != 8) return false;
    out->mode = (uint8_t)rd_u8(p + 0);
    out->flags = (uint8_t)rd_u8(p + 1);
    memcpy(out->room_code, p + 2, 6);
    return true;
}

size_t pong_write_match_start(uint8_t *out, size_t cap, uint16_t seq, const PongMATCH_START *m) {
    if (cap < 40) return 0;
    wr_header(out, PONG_MSG_MATCH_START, 32, seq);
    wr_u32(out + 8, (uint32_t)m->match_id);
    wr_u8(out + 12, (uint8_t)m->your_side);
    wr_u8(out + 13, (uint8_t)m->opp_platform);
    wr_u16(out + 14, (uint16_t)m->paddle_hq4);
    wr_u16(out + 16, (uint16_t)m->paddle_wq4);
    wr_u16(out + 18, (uint16_t)m->ball_rq4);
    wr_u16(out + 20, (uint16_t)m->max_paddle_spd_q4);
    wr_u8(out + 22, (uint8_t)m->win_score);
    wr_u8(out + 23, (uint8_t)m->match_flags);
    memcpy(out + 24, m->opp_name, 16);
    return 40;
}

bool pong_read_match_start(const uint8_t *p, uint16_t len, PongMATCH_START *out) {
    if (len != 32) return false;
    out->match_id = (uint32_t)rd_u32(p + 0);
    out->your_side = (uint8_t)rd_u8(p + 4);
    out->opp_platform = (uint8_t)rd_u8(p + 5);
    out->paddle_hq4 = (uint16_t)rd_u16(p + 6);
    out->paddle_wq4 = (uint16_t)rd_u16(p + 8);
    out->ball_rq4 = (uint16_t)rd_u16(p + 10);
    out->max_paddle_spd_q4 = (uint16_t)rd_u16(p + 12);
    out->win_score = (uint8_t)rd_u8(p + 14);
    out->match_flags = (uint8_t)rd_u8(p + 15);
    memcpy(out->opp_name, p + 16, 16);
    return true;
}

size_t pong_write_input(uint8_t *out, size_t cap, uint16_t seq, const PongINPUT *m) {
    if (cap < 20) return 0;
    wr_header(out, PONG_MSG_INPUT, 12, seq);
    wr_u32(out + 8, (uint32_t)m->input_seq);
    wr_u32(out + 12, (uint32_t)m->last_tick_seen);
    wr_u16(out + 16, (uint16_t)m->desired_yq4);
    wr_u8(out + 18, (uint8_t)m->buttons);
    wr_u8(out + 19, (uint8_t)m->flags);
    return 20;
}

bool pong_read_input(const uint8_t *p, uint16_t len, PongINPUT *out) {
    if (len != 12) return false;
    out->input_seq = (uint32_t)rd_u32(p + 0);
    out->last_tick_seen = (uint32_t)rd_u32(p + 4);
    out->desired_yq4 = (int16_t)rd_u16(p + 8);
    out->buttons = (uint8_t)rd_u8(p + 10);
    out->flags = (uint8_t)rd_u8(p + 11);
    return true;
}

size_t pong_write_snapshot(uint8_t *out, size_t cap, uint16_t seq, const PongSNAPSHOT *m) {
    if (cap < 32) return 0;
    wr_header(out, PONG_MSG_SNAPSHOT, 24, seq);
    wr_u32(out + 8, (uint32_t)m->tick);
    wr_u32(out + 12, (uint32_t)m->ack_input_seq);
    wr_u16(out + 16, (uint16_t)m->ball_xq4);
    wr_u16(out + 18, (uint16_t)m->ball_yq4);
    wr_u16(out + 20, (uint16_t)m->ball_vxq4);
    wr_u16(out + 22, (uint16_t)m->ball_vyq4);
    wr_u16(out + 24, (uint16_t)m->left_yq4);
    wr_u16(out + 26, (uint16_t)m->right_yq4);
    wr_u8(out + 28, (uint8_t)m->score_l);
    wr_u8(out + 29, (uint8_t)m->score_r);
    wr_u8(out + 30, (uint8_t)m->state);
    wr_u8(out + 31, (uint8_t)m->flags);
    return 32;
}

bool pong_read_snapshot(const uint8_t *p, uint16_t len, PongSNAPSHOT *out) {
    if (len != 24) return false;
    out->tick = (uint32_t)rd_u32(p + 0);
    out->ack_input_seq = (uint32_t)rd_u32(p + 4);
    out->ball_xq4 = (int16_t)rd_u16(p + 8);
    out->ball_yq4 = (int16_t)rd_u16(p + 10);
    out->ball_vxq4 = (int16_t)rd_u16(p + 12);
    out->ball_vyq4 = (int16_t)rd_u16(p + 14);
    out->left_yq4 = (int16_t)rd_u16(p + 16);
    out->right_yq4 = (int16_t)rd_u16(p + 18);
    out->score_l = (uint8_t)rd_u8(p + 20);
    out->score_r = (uint8_t)rd_u8(p + 21);
    out->state = (uint8_t)rd_u8(p + 22);
    out->flags = (uint8_t)rd_u8(p + 23);
    return true;
}

size_t pong_write_event(uint8_t *out, size_t cap, uint16_t seq, const PongEVENT *m) {
    if (cap < 16) return 0;
    wr_header(out, PONG_MSG_EVENT, 8, seq);
    wr_u32(out + 8, (uint32_t)m->tick);
    wr_u8(out + 12, (uint8_t)m->kind);
    wr_u8(out + 13, (uint8_t)m->a);
    wr_u8(out + 14, (uint8_t)m->b);
    wr_u8(out + 15, (uint8_t)m->c);
    return 16;
}

bool pong_read_event(const uint8_t *p, uint16_t len, PongEVENT *out) {
    if (len != 8) return false;
    out->tick = (uint32_t)rd_u32(p + 0);
    out->kind = (uint8_t)rd_u8(p + 4);
    out->a = (uint8_t)rd_u8(p + 5);
    out->b = (uint8_t)rd_u8(p + 6);
    out->c = (uint8_t)rd_u8(p + 7);
    return true;
}

size_t pong_write_ping(uint8_t *out, size_t cap, uint16_t seq, const PongPING *m) {
    if (cap < 16) return 0;
    wr_header(out, PONG_MSG_PING, 8, seq);
    wr_u32(out + 8, (uint32_t)m->client_time_ms);
    wr_u32(out + 12, (uint32_t)m->echo_server_time_ms);
    return 16;
}

bool pong_read_ping(const uint8_t *p, uint16_t len, PongPING *out) {
    if (len != 8) return false;
    out->client_time_ms = (uint32_t)rd_u32(p + 0);
    out->echo_server_time_ms = (uint32_t)rd_u32(p + 4);
    return true;
}

size_t pong_write_pong(uint8_t *out, size_t cap, uint16_t seq, const PongPONG *m) {
    if (cap < 20) return 0;
    wr_header(out, PONG_MSG_PONG, 12, seq);
    wr_u32(out + 8, (uint32_t)m->client_time_ms);
    wr_u32(out + 12, (uint32_t)m->server_time_ms);
    wr_u32(out + 16, (uint32_t)m->server_tick);
    return 20;
}

bool pong_read_pong(const uint8_t *p, uint16_t len, PongPONG *out) {
    if (len != 12) return false;
    out->client_time_ms = (uint32_t)rd_u32(p + 0);
    out->server_time_ms = (uint32_t)rd_u32(p + 4);
    out->server_tick = (uint32_t)rd_u32(p + 8);
    return true;
}

size_t pong_write_bye(uint8_t *out, size_t cap, uint16_t seq, const PongBYE *m) {
    if (cap < 12) return 0;
    wr_header(out, PONG_MSG_BYE, 4, seq);
    wr_u16(out + 8, (uint16_t)m->code);
    wr_u16(out + 10, (uint16_t)m->reserved);
    return 12;
}

bool pong_read_bye(const uint8_t *p, uint16_t len, PongBYE *out) {
    if (len != 4) return false;
    out->code = (uint16_t)rd_u16(p + 0);
    out->reserved = (uint16_t)rd_u16(p + 2);
    return true;
}

size_t pong_write_leave(uint8_t *out, size_t cap, uint16_t seq, const PongLEAVE *m) {
    if (cap < 8) return 0;
    wr_header(out, PONG_MSG_LEAVE, 0, seq);
    (void)m;
    return 8;
}

bool pong_read_leave(const uint8_t *p, uint16_t len, PongLEAVE *out) {
    if (len != 0) return false;
    (void)p; out->_empty = 0;
    return true;
}

size_t pong_write_resume(uint8_t *out, size_t cap, uint16_t seq, const PongRESUME *m) {
    if (cap < 28) return 0;
    wr_header(out, PONG_MSG_RESUME, 20, seq);
    memcpy(out + 8, m->session_id, 16);
    wr_u32(out + 24, (uint32_t)m->last_tick_seen);
    return 28;
}

bool pong_read_resume(const uint8_t *p, uint16_t len, PongRESUME *out) {
    if (len != 20) return false;
    memcpy(out->session_id, p + 0, 16);
    out->last_tick_seen = (uint32_t)rd_u32(p + 16);
    return true;
}
