/* GENERATED BY tools/gen-protocol.mjs FROM shared/protocol.json -- DO NOT EDIT. */
#ifndef PONG_PROTO_H
#define PONG_PROTO_H

/*
 * Pure C99. Deliberately includes NO libctru headers -- this file is compiled
 * unchanged by the host test (clang) and by a future Wii client (devkitPPC).
 * Keeping it platform-free is what makes those reuses possible.
 *
 * All access is by explicit byte offset with memcpy into locals. Never cast a
 * byte buffer to a struct: ARM11 alignment and padding rules would silently
 * disagree with the wire layout.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PONG_PROTOCOL_VERSION 1
#define PONG_HEADER_BYTES 8
#define PONG_MAGIC0 80
#define PONG_MAGIC1 71

#define PONG_Q4_SHIFT 4
#define PONG_FIELD_W 800
#define PONG_FIELD_H 480
#define PONG_TICK_HZ 60
#define PONG_SNAPSHOT_HZ 30
#define PONG_PADDLE_W 12
#define PONG_PADDLE_H 80
#define PONG_PADDLE_X_L 24
#define PONG_PADDLE_X_R 776
#define PONG_BALL_R 8
#define PONG_MAX_PADDLE_SPEED_Q4 192
#define PONG_BALL_SPEED_START_Q4 80
#define PONG_BALL_SPEED_STEP_Q4 6
#define PONG_BALL_SPEED_MAX_Q4 176
#define PONG_BALL_SPEED_MAX_SLOW_Q4 144
#define PONG_BALL_MAX_ANGLE_STEPS 38
#define PONG_WIN_SCORE 7
#define PONG_COUNTDOWN_TICKS 180
#define PONG_GOAL_FREEZE_TICKS 90
#define PONG_SNAP_RING 60
#define PONG_SNAP_BATCH_MAX 8
#define PONG_NAME_BYTES 16
#define PONG_ROOM_CODE_BYTES 6
#define PONG_SESSION_ID_BYTES 16
#define PONG_MAX_FRAME_BYTES 64
#define PONG_GRACE_MS 30000
#define PONG_LONGPOLL_HOLD_MS 20000

#define PONG_FIELD_W_Q4 (PONG_FIELD_W << PONG_Q4_SHIFT)
#define PONG_FIELD_H_Q4 (PONG_FIELD_H << PONG_Q4_SHIFT)

/* Q4 -> 3DS top-screen pixels: /16 for fixed point, /2 for the 800x480 -> 400x240
 * mapping. One shift, no floats, no rounding drift. */
#define PONG_Q4_TO_TOPSCREEN(q) ((q) >> (PONG_Q4_SHIFT + 1))

typedef enum {
    PONG_PLATFORM_UNKNOWN = 0,
    PONG_PLATFORM_WEB = 1,
    PONG_PLATFORM_N3DS = 2,
    PONG_PLATFORM_WII = 3,
    PONG_PLATFORM_PC = 4,
    PONG_PLATFORM_VITA = 5,
} PongPlatform;

typedef enum {
    PONG_TRANSPORT_KIND_TCP = 0,
    PONG_TRANSPORT_KIND_WS = 1,
    PONG_TRANSPORT_KIND_SSE = 2,
    PONG_TRANSPORT_KIND_LONGPOLL = 3,
    PONG_TRANSPORT_KIND_RR = 4,
} PongTransportKind;

typedef enum {
    PONG_JOIN_MODE_QUICKMATCH = 0,
    PONG_JOIN_MODE_ROOM_CODE = 1,
    PONG_JOIN_MODE_VS_BOT = 2,
} PongJoinMode;

typedef enum {
    PONG_MATCH_STATE_LOBBY = 0,
    PONG_MATCH_STATE_COUNTDOWN = 1,
    PONG_MATCH_STATE_PLAY = 2,
    PONG_MATCH_STATE_GOAL_FREEZE = 3,
    PONG_MATCH_STATE_GAME_OVER = 4,
    PONG_MATCH_STATE_OPP_LOST = 5,
} PongMatchState;

typedef enum {
    PONG_EVENT_KIND_GOAL = 1,
    PONG_EVENT_KIND_MATCH_OVER = 2,
    PONG_EVENT_KIND_OPP_LEFT = 3,
    PONG_EVENT_KIND_OPP_REJOINED = 4,
    PONG_EVENT_KIND_COUNTDOWN_START = 5,
    PONG_EVENT_KIND_PADDLE_HIT = 6,
    PONG_EVENT_KIND_WALL_HIT = 7,
} PongEventKind;

typedef enum {
    PONG_BYE_CODE_NORMAL = 1,
    PONG_BYE_CODE_TIMEOUT = 2,
    PONG_BYE_CODE_PROTO_ERR = 3,
    PONG_BYE_CODE_VERSION_MISMATCH = 4,
    PONG_BYE_CODE_ROOM_FULL = 5,
    PONG_BYE_CODE_SESSION_UNKNOWN = 6,
} PongByeCode;

typedef enum {
    PONG_SNAP_FLAG_KEYFRAME = 1,
    PONG_SNAP_FLAG_OPP_CONNECTED = 2,
    PONG_SNAP_FLAG_SLOW_MODE = 4,
} PongSnapFlag;

typedef enum {
    PONG_MATCH_FLAG_SLOW_MODE = 1,
} PongMatchFlag;

typedef enum {
    PONG_BUTTON_BIT_CONTINUE = 1,
    PONG_BUTTON_BIT_PAUSE = 2,
    PONG_BUTTON_BIT_REMATCH = 4,
} PongButtonBit;

typedef enum {
    PONG_MSG_HELLO = 1,
    PONG_MSG_WELCOME = 2,
    PONG_MSG_JOIN = 3,
    PONG_MSG_MATCH_START = 4,
    PONG_MSG_INPUT = 5,
    PONG_MSG_SNAPSHOT = 6,
    PONG_MSG_EVENT = 7,
    PONG_MSG_PING = 8,
    PONG_MSG_PONG = 9,
    PONG_MSG_BYE = 10,
    PONG_MSG_LEAVE = 11,
    PONG_MSG_RESUME = 13,
} PongMsgType;

#define PONG_HELLO_BYTES 24
typedef struct {
    uint8_t platform;
    uint8_t transport;
    uint16_t caps;
    uint8_t name[16];
    uint32_t build_id;
} PongHELLO;

#define PONG_WELCOME_BYTES 28
typedef struct {
    uint8_t session_id[16];
    uint32_t server_time_ms;
    uint16_t tick_rate;
    uint16_t snapshot_rate;
    uint16_t field_w;
    uint16_t field_h;
} PongWELCOME;

#define PONG_JOIN_BYTES 8
typedef struct {
    uint8_t mode;
    uint8_t flags;
    uint8_t room_code[6];
} PongJOIN;

#define PONG_MATCH_START_BYTES 32
typedef struct {
    uint32_t match_id;
    uint8_t your_side;
    uint8_t opp_platform;
    uint16_t paddle_hq4;
    uint16_t paddle_wq4;
    uint16_t ball_rq4;
    uint16_t max_paddle_spd_q4;
    uint8_t win_score;
    uint8_t match_flags;
    uint8_t opp_name[16];
} PongMATCH_START;

#define PONG_INPUT_BYTES 12
typedef struct {
    uint32_t input_seq;
    uint32_t last_tick_seen;
    int16_t desired_yq4;
    uint8_t buttons;
    uint8_t flags;
} PongINPUT;

#define PONG_SNAPSHOT_BYTES 24
typedef struct {
    uint32_t tick;
    uint32_t ack_input_seq;
    int16_t ball_xq4;
    int16_t ball_yq4;
    int16_t ball_vxq4;
    int16_t ball_vyq4;
    int16_t left_yq4;
    int16_t right_yq4;
    uint8_t score_l;
    uint8_t score_r;
    uint8_t state;
    uint8_t flags;
} PongSNAPSHOT;

#define PONG_EVENT_BYTES 8
typedef struct {
    uint32_t tick;
    uint8_t kind;
    uint8_t a;
    uint8_t b;
    uint8_t c;
} PongEVENT;

#define PONG_PING_BYTES 8
typedef struct {
    uint32_t client_time_ms;
    uint32_t echo_server_time_ms;
} PongPING;

#define PONG_PONG_BYTES 12
typedef struct {
    uint32_t client_time_ms;
    uint32_t server_time_ms;
    uint32_t server_tick;
} PongPONG;

#define PONG_BYE_BYTES 4
typedef struct {
    uint16_t code;
    uint16_t reserved;
} PongBYE;

#define PONG_LEAVE_BYTES 0
typedef struct {
    uint8_t _empty; /* no fields */
} PongLEAVE;

#define PONG_RESUME_BYTES 20
typedef struct {
    uint8_t session_id[16];
    uint32_t last_tick_seen;
} PongRESUME;

/* ------------------------------------------------------------ framing */

typedef struct {
    uint8_t  type;
    uint16_t seq;
    uint16_t length;
    const uint8_t *payload;
} PongFrame;

typedef enum {
    PONG_PARSE_OK = 0,
    PONG_PARSE_NEED_MORE = 1,  /* partial frame at tail; keep buffering */
    PONG_PARSE_BAD_MAGIC = 2,
    PONG_PARSE_BAD_VERSION = 3,
    PONG_PARSE_BAD_LENGTH = 4,
} PongParseResult;

/* Pops one frame from `buf`. On PONG_PARSE_OK, *consumed is the frame size. */
PongParseResult pong_parse_frame(const uint8_t *buf, size_t len,
                                 PongFrame *out, size_t *consumed);

/* Expected payload size for a type, or -1 if the type is unknown. */
int pong_payload_bytes(uint8_t type);

/* NUL-pad an ASCII string into a fixed-width field. */
void pong_pad_bytes(uint8_t *dst, size_t dstlen, const char *src);

/* HELLO (c2s) -- 32 bytes framed */
size_t pong_write_hello(uint8_t *out, size_t cap, uint16_t seq, const PongHELLO *m);
bool   pong_read_hello(const uint8_t *p, uint16_t len, PongHELLO *out);

/* WELCOME (s2c) -- 36 bytes framed */
size_t pong_write_welcome(uint8_t *out, size_t cap, uint16_t seq, const PongWELCOME *m);
bool   pong_read_welcome(const uint8_t *p, uint16_t len, PongWELCOME *out);

/* JOIN (c2s) -- 16 bytes framed */
size_t pong_write_join(uint8_t *out, size_t cap, uint16_t seq, const PongJOIN *m);
bool   pong_read_join(const uint8_t *p, uint16_t len, PongJOIN *out);

/* MATCH_START (s2c) -- 40 bytes framed */
size_t pong_write_match_start(uint8_t *out, size_t cap, uint16_t seq, const PongMATCH_START *m);
bool   pong_read_match_start(const uint8_t *p, uint16_t len, PongMATCH_START *out);

/* INPUT (c2s) -- 20 bytes framed */
size_t pong_write_input(uint8_t *out, size_t cap, uint16_t seq, const PongINPUT *m);
bool   pong_read_input(const uint8_t *p, uint16_t len, PongINPUT *out);

/* SNAPSHOT (s2c) -- 32 bytes framed */
size_t pong_write_snapshot(uint8_t *out, size_t cap, uint16_t seq, const PongSNAPSHOT *m);
bool   pong_read_snapshot(const uint8_t *p, uint16_t len, PongSNAPSHOT *out);

/* EVENT (s2c) -- 16 bytes framed */
size_t pong_write_event(uint8_t *out, size_t cap, uint16_t seq, const PongEVENT *m);
bool   pong_read_event(const uint8_t *p, uint16_t len, PongEVENT *out);

/* PING (c2s) -- 16 bytes framed */
size_t pong_write_ping(uint8_t *out, size_t cap, uint16_t seq, const PongPING *m);
bool   pong_read_ping(const uint8_t *p, uint16_t len, PongPING *out);

/* PONG (s2c) -- 20 bytes framed */
size_t pong_write_pong(uint8_t *out, size_t cap, uint16_t seq, const PongPONG *m);
bool   pong_read_pong(const uint8_t *p, uint16_t len, PongPONG *out);

/* BYE (s2c) -- 12 bytes framed */
size_t pong_write_bye(uint8_t *out, size_t cap, uint16_t seq, const PongBYE *m);
bool   pong_read_bye(const uint8_t *p, uint16_t len, PongBYE *out);

/* LEAVE (c2s) -- 8 bytes framed */
size_t pong_write_leave(uint8_t *out, size_t cap, uint16_t seq, const PongLEAVE *m);
bool   pong_read_leave(const uint8_t *p, uint16_t len, PongLEAVE *out);

/* RESUME (c2s) -- 28 bytes framed */
size_t pong_write_resume(uint8_t *out, size_t cap, uint16_t seq, const PongRESUME *m);
bool   pong_read_resume(const uint8_t *p, uint16_t len, PongRESUME *out);

#ifdef __cplusplus
}
#endif

#endif /* PONG_PROTO_H */
