/* GENERATED BY tools/gen-protocol.mjs FROM shared/protocol.json -- DO NOT EDIT. */
#ifndef PONG_GOLDEN_DATA_H
#define PONG_GOLDEN_DATA_H

/*
 * Canonical frames produced by the TypeScript encoder, plus the exact field
 * values that produced them.
 *
 * The C codec decodes these bytes and every field is asserted against the
 * literal the TS side used. Asserting FIELDS rather than doing a C-only
 * encode/decode round-trip matters: a round-trip passes happily when read and
 * write share the same wrong offset. This does not.
 */

#include <stdint.h>
#include <string.h>
#include "../source/net/pong_proto.h"

#ifndef PONG_GOLDEN_FAIL
#include <stdio.h>
#define PONG_GOLDEN_FAIL(msg, field) \
    do { printf("  FAIL %s.%s\n", msg, field); return 1; } while (0)
#endif

static const uint8_t GOLDEN_HELLO[32] = {
    0x50, 0x47, 0x01, 0x01, 0x18, 0x00, 0x00, 0x00, 0x39, 0xea, 0x9b, 0x23,
    0x05, 0x0c, 0x13, 0x1a, 0x21, 0x28, 0x2f, 0x36, 0x3d, 0x44, 0x4b, 0x52,
    0x59, 0x60, 0x67, 0x6e, 0x0d, 0xb2, 0x55, 0x5c,
};
static const uint8_t GOLDEN_WELCOME[36] = {
    0x50, 0x47, 0x01, 0x02, 0x1c, 0x00, 0xe5, 0x03, 0x01, 0x08, 0x0f, 0x16,
    0x1d, 0x24, 0x2b, 0x32, 0x39, 0x40, 0x47, 0x4e, 0x55, 0x5c, 0x63, 0x6a,
    0x80, 0x69, 0x78, 0xe3, 0x44, 0x50, 0xa6, 0x43, 0x08, 0x37, 0x6a, 0x2a,
};
static const uint8_t GOLDEN_JOIN[16] = {
    0x50, 0x47, 0x01, 0x03, 0x08, 0x00, 0xca, 0x07, 0xa7, 0x58, 0x03, 0x0a,
    0x11, 0x18, 0x1f, 0x26,
};
static const uint8_t GOLDEN_MATCH_START[40] = {
    0x50, 0x47, 0x01, 0x04, 0x20, 0x00, 0xaf, 0x0b, 0xde, 0x0a, 0x02, 0x00,
    0xa2, 0x53, 0x04, 0xe5, 0x66, 0xd8, 0xc8, 0xcb, 0x2a, 0xbf, 0x8c, 0x3d,
    0x11, 0x18, 0x1f, 0x26, 0x2d, 0x34, 0x3b, 0x42, 0x49, 0x50, 0x57, 0x5e,
    0x65, 0x6c, 0x73, 0x7a,
};
static const uint8_t GOLDEN_INPUT[20] = {
    0x50, 0x47, 0x01, 0x05, 0x0c, 0x00, 0x94, 0x0f, 0x15, 0xa9, 0x02, 0x00,
    0xd9, 0x8f, 0xe0, 0x78, 0x9d, 0xf6, 0xff, 0xb0,
};
static const uint8_t GOLDEN_SNAPSHOT[32] = {
    0x50, 0x47, 0x01, 0x06, 0x18, 0x00, 0x79, 0x13, 0x4c, 0x47, 0x03, 0x00,
    0x10, 0x2e, 0xe1, 0x78, 0xd4, 0x94, 0x36, 0x88, 0x98, 0x7b, 0xfa, 0x6e,
    0x5c, 0x62, 0xbe, 0x55, 0x20, 0xd1, 0x82, 0x33,
};
static const uint8_t GOLDEN_EVENT[16] = {
    0x50, 0x47, 0x01, 0x07, 0x08, 0x00, 0x5e, 0x17, 0x83, 0xe5, 0x03, 0x00,
    0x47, 0xf8, 0xa9, 0x5a,
};
static const uint8_t GOLDEN_PING[16] = {
    0x50, 0x47, 0x01, 0x08, 0x08, 0x00, 0x43, 0x1b, 0xba, 0x83, 0x04, 0x00,
    0x7e, 0x6a, 0xe2, 0x78,
};
static const uint8_t GOLDEN_PONG[20] = {
    0x50, 0x47, 0x01, 0x09, 0x0c, 0x00, 0x28, 0x1f, 0xf1, 0x21, 0x05, 0x00,
    0xb5, 0x08, 0xe3, 0x78, 0x79, 0xef, 0xc0, 0xf1,
};
static const uint8_t GOLDEN_BYE[12] = {
    0x50, 0x47, 0x01, 0x0a, 0x04, 0x00, 0x0d, 0x23, 0x28, 0xc0, 0x8a, 0xb3,
};
static const uint8_t GOLDEN_LEAVE[8] = {
    0x50, 0x47, 0x01, 0x0b, 0x00, 0x00, 0xf2, 0x26,
};
static const uint8_t GOLDEN_RESUME[28] = {
    0x50, 0x47, 0x01, 0x0d, 0x14, 0x00, 0xd7, 0x2a, 0x01, 0x08, 0x0f, 0x16,
    0x1d, 0x24, 0x2b, 0x32, 0x39, 0x40, 0x47, 0x4e, 0x55, 0x5c, 0x63, 0x6a,
    0xa6, 0x97, 0x7e, 0xe3,
};

static int pong_golden_check_hello(void) {
    PongFrame fr;
    size_t used = 0;
    PongHELLO m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_HELLO, sizeof GOLDEN_HELLO, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("HELLO", "<frame parse>");
    if (used != sizeof GOLDEN_HELLO) PONG_GOLDEN_FAIL("HELLO", "<consumed>");
    if (fr.type != PONG_MSG_HELLO) PONG_GOLDEN_FAIL("HELLO", "<type>");
    if (fr.seq != 0) PONG_GOLDEN_FAIL("HELLO", "<seq>");
    if (fr.length != 24) PONG_GOLDEN_FAIL("HELLO", "<length>");
    if (!pong_read_hello(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("HELLO", "<decode>");
    if (m.platform != (uint8_t)57) PONG_GOLDEN_FAIL("HELLO", "platform");
    if (m.transport != (uint8_t)234) PONG_GOLDEN_FAIL("HELLO", "transport");
    if (m.caps != (uint16_t)9115) PONG_GOLDEN_FAIL("HELLO", "caps");
    { static const uint8_t exp[16] = { 0x05, 0x0c, 0x13, 0x1a, 0x21, 0x28, 0x2f, 0x36, 0x3d, 0x44, 0x4b, 0x52, 0x59, 0x60, 0x67, 0x6e };
      if (memcmp(m.name, exp, 16) != 0) PONG_GOLDEN_FAIL("HELLO", "name"); }
    if (m.build_id != (uint32_t)1549120013) PONG_GOLDEN_FAIL("HELLO", "buildId");
    { uint8_t back[32];
      size_t n = pong_write_hello(back, sizeof back, 0, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("HELLO", "<encode size>");
      if (memcmp(back, GOLDEN_HELLO, sizeof back) != 0) PONG_GOLDEN_FAIL("HELLO", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_welcome(void) {
    PongFrame fr;
    size_t used = 0;
    PongWELCOME m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_WELCOME, sizeof GOLDEN_WELCOME, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("WELCOME", "<frame parse>");
    if (used != sizeof GOLDEN_WELCOME) PONG_GOLDEN_FAIL("WELCOME", "<consumed>");
    if (fr.type != PONG_MSG_WELCOME) PONG_GOLDEN_FAIL("WELCOME", "<type>");
    if (fr.seq != 997) PONG_GOLDEN_FAIL("WELCOME", "<seq>");
    if (fr.length != 28) PONG_GOLDEN_FAIL("WELCOME", "<length>");
    if (!pong_read_welcome(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("WELCOME", "<decode>");
    { static const uint8_t exp[16] = { 0x01, 0x08, 0x0f, 0x16, 0x1d, 0x24, 0x2b, 0x32, 0x39, 0x40, 0x47, 0x4e, 0x55, 0x5c, 0x63, 0x6a };
      if (memcmp(m.session_id, exp, 16) != 0) PONG_GOLDEN_FAIL("WELCOME", "sessionId"); }
    if (m.server_time_ms != (uint32_t)3816319360) PONG_GOLDEN_FAIL("WELCOME", "serverTimeMs");
    if (m.tick_rate != (uint16_t)20548) PONG_GOLDEN_FAIL("WELCOME", "tickRate");
    if (m.snapshot_rate != (uint16_t)17318) PONG_GOLDEN_FAIL("WELCOME", "snapshotRate");
    if (m.field_w != (uint16_t)14088) PONG_GOLDEN_FAIL("WELCOME", "fieldW");
    if (m.field_h != (uint16_t)10858) PONG_GOLDEN_FAIL("WELCOME", "fieldH");
    { uint8_t back[36];
      size_t n = pong_write_welcome(back, sizeof back, 997, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("WELCOME", "<encode size>");
      if (memcmp(back, GOLDEN_WELCOME, sizeof back) != 0) PONG_GOLDEN_FAIL("WELCOME", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_join(void) {
    PongFrame fr;
    size_t used = 0;
    PongJOIN m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_JOIN, sizeof GOLDEN_JOIN, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("JOIN", "<frame parse>");
    if (used != sizeof GOLDEN_JOIN) PONG_GOLDEN_FAIL("JOIN", "<consumed>");
    if (fr.type != PONG_MSG_JOIN) PONG_GOLDEN_FAIL("JOIN", "<type>");
    if (fr.seq != 1994) PONG_GOLDEN_FAIL("JOIN", "<seq>");
    if (fr.length != 8) PONG_GOLDEN_FAIL("JOIN", "<length>");
    if (!pong_read_join(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("JOIN", "<decode>");
    if (m.mode != (uint8_t)167) PONG_GOLDEN_FAIL("JOIN", "mode");
    if (m.flags != (uint8_t)88) PONG_GOLDEN_FAIL("JOIN", "flags");
    { static const uint8_t exp[6] = { 0x03, 0x0a, 0x11, 0x18, 0x1f, 0x26 };
      if (memcmp(m.room_code, exp, 6) != 0) PONG_GOLDEN_FAIL("JOIN", "roomCode"); }
    { uint8_t back[16];
      size_t n = pong_write_join(back, sizeof back, 1994, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("JOIN", "<encode size>");
      if (memcmp(back, GOLDEN_JOIN, sizeof back) != 0) PONG_GOLDEN_FAIL("JOIN", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_match_start(void) {
    PongFrame fr;
    size_t used = 0;
    PongMATCH_START m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_MATCH_START, sizeof GOLDEN_MATCH_START, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("MATCH_START", "<frame parse>");
    if (used != sizeof GOLDEN_MATCH_START) PONG_GOLDEN_FAIL("MATCH_START", "<consumed>");
    if (fr.type != PONG_MSG_MATCH_START) PONG_GOLDEN_FAIL("MATCH_START", "<type>");
    if (fr.seq != 2991) PONG_GOLDEN_FAIL("MATCH_START", "<seq>");
    if (fr.length != 32) PONG_GOLDEN_FAIL("MATCH_START", "<length>");
    if (!pong_read_match_start(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("MATCH_START", "<decode>");
    if (m.match_id != (uint32_t)133854) PONG_GOLDEN_FAIL("MATCH_START", "matchId");
    if (m.your_side != (uint8_t)162) PONG_GOLDEN_FAIL("MATCH_START", "yourSide");
    if (m.opp_platform != (uint8_t)83) PONG_GOLDEN_FAIL("MATCH_START", "oppPlatform");
    if (m.paddle_hq4 != (uint16_t)58628) PONG_GOLDEN_FAIL("MATCH_START", "paddleHQ4");
    if (m.paddle_wq4 != (uint16_t)55398) PONG_GOLDEN_FAIL("MATCH_START", "paddleWQ4");
    if (m.ball_rq4 != (uint16_t)52168) PONG_GOLDEN_FAIL("MATCH_START", "ballRQ4");
    if (m.max_paddle_spd_q4 != (uint16_t)48938) PONG_GOLDEN_FAIL("MATCH_START", "maxPaddleSpdQ4");
    if (m.win_score != (uint8_t)140) PONG_GOLDEN_FAIL("MATCH_START", "winScore");
    if (m.match_flags != (uint8_t)61) PONG_GOLDEN_FAIL("MATCH_START", "matchFlags");
    { static const uint8_t exp[16] = { 0x11, 0x18, 0x1f, 0x26, 0x2d, 0x34, 0x3b, 0x42, 0x49, 0x50, 0x57, 0x5e, 0x65, 0x6c, 0x73, 0x7a };
      if (memcmp(m.opp_name, exp, 16) != 0) PONG_GOLDEN_FAIL("MATCH_START", "oppName"); }
    { uint8_t back[40];
      size_t n = pong_write_match_start(back, sizeof back, 2991, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("MATCH_START", "<encode size>");
      if (memcmp(back, GOLDEN_MATCH_START, sizeof back) != 0) PONG_GOLDEN_FAIL("MATCH_START", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_input(void) {
    PongFrame fr;
    size_t used = 0;
    PongINPUT m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_INPUT, sizeof GOLDEN_INPUT, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("INPUT", "<frame parse>");
    if (used != sizeof GOLDEN_INPUT) PONG_GOLDEN_FAIL("INPUT", "<consumed>");
    if (fr.type != PONG_MSG_INPUT) PONG_GOLDEN_FAIL("INPUT", "<type>");
    if (fr.seq != 3988) PONG_GOLDEN_FAIL("INPUT", "<seq>");
    if (fr.length != 12) PONG_GOLDEN_FAIL("INPUT", "<length>");
    if (!pong_read_input(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("INPUT", "<decode>");
    if (m.input_seq != (uint32_t)174357) PONG_GOLDEN_FAIL("INPUT", "inputSeq");
    if (m.last_tick_seen != (uint32_t)2027982809) PONG_GOLDEN_FAIL("INPUT", "lastTickSeen");
    if (m.desired_yq4 != (int16_t)-2403) PONG_GOLDEN_FAIL("INPUT", "desiredYQ4");
    if (m.buttons != (uint8_t)255) PONG_GOLDEN_FAIL("INPUT", "buttons");
    if (m.flags != (uint8_t)176) PONG_GOLDEN_FAIL("INPUT", "flags");
    { uint8_t back[20];
      size_t n = pong_write_input(back, sizeof back, 3988, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("INPUT", "<encode size>");
      if (memcmp(back, GOLDEN_INPUT, sizeof back) != 0) PONG_GOLDEN_FAIL("INPUT", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_snapshot(void) {
    PongFrame fr;
    size_t used = 0;
    PongSNAPSHOT m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_SNAPSHOT, sizeof GOLDEN_SNAPSHOT, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("SNAPSHOT", "<frame parse>");
    if (used != sizeof GOLDEN_SNAPSHOT) PONG_GOLDEN_FAIL("SNAPSHOT", "<consumed>");
    if (fr.type != PONG_MSG_SNAPSHOT) PONG_GOLDEN_FAIL("SNAPSHOT", "<type>");
    if (fr.seq != 4985) PONG_GOLDEN_FAIL("SNAPSHOT", "<seq>");
    if (fr.length != 24) PONG_GOLDEN_FAIL("SNAPSHOT", "<length>");
    if (!pong_read_snapshot(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("SNAPSHOT", "<decode>");
    if (m.tick != (uint32_t)214860) PONG_GOLDEN_FAIL("SNAPSHOT", "tick");
    if (m.ack_input_seq != (uint32_t)2028023312) PONG_GOLDEN_FAIL("SNAPSHOT", "ackInputSeq");
    if (m.ball_xq4 != (int16_t)-27436) PONG_GOLDEN_FAIL("SNAPSHOT", "ballXQ4");
    if (m.ball_yq4 != (int16_t)-30666) PONG_GOLDEN_FAIL("SNAPSHOT", "ballYQ4");
    if (m.ball_vxq4 != (int16_t)31640) PONG_GOLDEN_FAIL("SNAPSHOT", "ballVXQ4");
    if (m.ball_vyq4 != (int16_t)28410) PONG_GOLDEN_FAIL("SNAPSHOT", "ballVYQ4");
    if (m.left_yq4 != (int16_t)25180) PONG_GOLDEN_FAIL("SNAPSHOT", "leftYQ4");
    if (m.right_yq4 != (int16_t)21950) PONG_GOLDEN_FAIL("SNAPSHOT", "rightYQ4");
    if (m.score_l != (uint8_t)32) PONG_GOLDEN_FAIL("SNAPSHOT", "scoreL");
    if (m.score_r != (uint8_t)209) PONG_GOLDEN_FAIL("SNAPSHOT", "scoreR");
    if (m.state != (uint8_t)130) PONG_GOLDEN_FAIL("SNAPSHOT", "state");
    if (m.flags != (uint8_t)51) PONG_GOLDEN_FAIL("SNAPSHOT", "flags");
    { uint8_t back[32];
      size_t n = pong_write_snapshot(back, sizeof back, 4985, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("SNAPSHOT", "<encode size>");
      if (memcmp(back, GOLDEN_SNAPSHOT, sizeof back) != 0) PONG_GOLDEN_FAIL("SNAPSHOT", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_event(void) {
    PongFrame fr;
    size_t used = 0;
    PongEVENT m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_EVENT, sizeof GOLDEN_EVENT, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("EVENT", "<frame parse>");
    if (used != sizeof GOLDEN_EVENT) PONG_GOLDEN_FAIL("EVENT", "<consumed>");
    if (fr.type != PONG_MSG_EVENT) PONG_GOLDEN_FAIL("EVENT", "<type>");
    if (fr.seq != 5982) PONG_GOLDEN_FAIL("EVENT", "<seq>");
    if (fr.length != 8) PONG_GOLDEN_FAIL("EVENT", "<length>");
    if (!pong_read_event(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("EVENT", "<decode>");
    if (m.tick != (uint32_t)255363) PONG_GOLDEN_FAIL("EVENT", "tick");
    if (m.kind != (uint8_t)71) PONG_GOLDEN_FAIL("EVENT", "kind");
    if (m.a != (uint8_t)248) PONG_GOLDEN_FAIL("EVENT", "a");
    if (m.b != (uint8_t)169) PONG_GOLDEN_FAIL("EVENT", "b");
    if (m.c != (uint8_t)90) PONG_GOLDEN_FAIL("EVENT", "c");
    { uint8_t back[16];
      size_t n = pong_write_event(back, sizeof back, 5982, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("EVENT", "<encode size>");
      if (memcmp(back, GOLDEN_EVENT, sizeof back) != 0) PONG_GOLDEN_FAIL("EVENT", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_ping(void) {
    PongFrame fr;
    size_t used = 0;
    PongPING m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_PING, sizeof GOLDEN_PING, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("PING", "<frame parse>");
    if (used != sizeof GOLDEN_PING) PONG_GOLDEN_FAIL("PING", "<consumed>");
    if (fr.type != PONG_MSG_PING) PONG_GOLDEN_FAIL("PING", "<type>");
    if (fr.seq != 6979) PONG_GOLDEN_FAIL("PING", "<seq>");
    if (fr.length != 8) PONG_GOLDEN_FAIL("PING", "<length>");
    if (!pong_read_ping(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("PING", "<decode>");
    if (m.client_time_ms != (uint32_t)295866) PONG_GOLDEN_FAIL("PING", "clientTimeMs");
    if (m.echo_server_time_ms != (uint32_t)2028104318) PONG_GOLDEN_FAIL("PING", "echoServerTimeMs");
    { uint8_t back[16];
      size_t n = pong_write_ping(back, sizeof back, 6979, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("PING", "<encode size>");
      if (memcmp(back, GOLDEN_PING, sizeof back) != 0) PONG_GOLDEN_FAIL("PING", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_pong(void) {
    PongFrame fr;
    size_t used = 0;
    PongPONG m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_PONG, sizeof GOLDEN_PONG, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("PONG", "<frame parse>");
    if (used != sizeof GOLDEN_PONG) PONG_GOLDEN_FAIL("PONG", "<consumed>");
    if (fr.type != PONG_MSG_PONG) PONG_GOLDEN_FAIL("PONG", "<type>");
    if (fr.seq != 7976) PONG_GOLDEN_FAIL("PONG", "<seq>");
    if (fr.length != 12) PONG_GOLDEN_FAIL("PONG", "<length>");
    if (!pong_read_pong(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("PONG", "<decode>");
    if (m.client_time_ms != (uint32_t)336369) PONG_GOLDEN_FAIL("PONG", "clientTimeMs");
    if (m.server_time_ms != (uint32_t)2028144821) PONG_GOLDEN_FAIL("PONG", "serverTimeMs");
    if (m.server_tick != (uint32_t)4055953273) PONG_GOLDEN_FAIL("PONG", "serverTick");
    { uint8_t back[20];
      size_t n = pong_write_pong(back, sizeof back, 7976, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("PONG", "<encode size>");
      if (memcmp(back, GOLDEN_PONG, sizeof back) != 0) PONG_GOLDEN_FAIL("PONG", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_bye(void) {
    PongFrame fr;
    size_t used = 0;
    PongBYE m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_BYE, sizeof GOLDEN_BYE, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("BYE", "<frame parse>");
    if (used != sizeof GOLDEN_BYE) PONG_GOLDEN_FAIL("BYE", "<consumed>");
    if (fr.type != PONG_MSG_BYE) PONG_GOLDEN_FAIL("BYE", "<type>");
    if (fr.seq != 8973) PONG_GOLDEN_FAIL("BYE", "<seq>");
    if (fr.length != 4) PONG_GOLDEN_FAIL("BYE", "<length>");
    if (!pong_read_bye(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("BYE", "<decode>");
    if (m.code != (uint16_t)49192) PONG_GOLDEN_FAIL("BYE", "code");
    if (m.reserved != (uint16_t)45962) PONG_GOLDEN_FAIL("BYE", "reserved");
    { uint8_t back[12];
      size_t n = pong_write_bye(back, sizeof back, 8973, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("BYE", "<encode size>");
      if (memcmp(back, GOLDEN_BYE, sizeof back) != 0) PONG_GOLDEN_FAIL("BYE", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_leave(void) {
    PongFrame fr;
    size_t used = 0;
    PongLEAVE m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_LEAVE, sizeof GOLDEN_LEAVE, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("LEAVE", "<frame parse>");
    if (used != sizeof GOLDEN_LEAVE) PONG_GOLDEN_FAIL("LEAVE", "<consumed>");
    if (fr.type != PONG_MSG_LEAVE) PONG_GOLDEN_FAIL("LEAVE", "<type>");
    if (fr.seq != 9970) PONG_GOLDEN_FAIL("LEAVE", "<seq>");
    if (fr.length != 0) PONG_GOLDEN_FAIL("LEAVE", "<length>");
    if (!pong_read_leave(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("LEAVE", "<decode>");
    { uint8_t back[8];
      size_t n = pong_write_leave(back, sizeof back, 9970, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("LEAVE", "<encode size>");
      if (memcmp(back, GOLDEN_LEAVE, sizeof back) != 0) PONG_GOLDEN_FAIL("LEAVE", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_resume(void) {
    PongFrame fr;
    size_t used = 0;
    PongRESUME m;
    memset(&m, 0, sizeof m);
    if (pong_parse_frame(GOLDEN_RESUME, sizeof GOLDEN_RESUME, &fr, &used) != PONG_PARSE_OK)
        PONG_GOLDEN_FAIL("RESUME", "<frame parse>");
    if (used != sizeof GOLDEN_RESUME) PONG_GOLDEN_FAIL("RESUME", "<consumed>");
    if (fr.type != PONG_MSG_RESUME) PONG_GOLDEN_FAIL("RESUME", "<type>");
    if (fr.seq != 10967) PONG_GOLDEN_FAIL("RESUME", "<seq>");
    if (fr.length != 20) PONG_GOLDEN_FAIL("RESUME", "<length>");
    if (!pong_read_resume(fr.payload, fr.length, &m)) PONG_GOLDEN_FAIL("RESUME", "<decode>");
    { static const uint8_t exp[16] = { 0x01, 0x08, 0x0f, 0x16, 0x1d, 0x24, 0x2b, 0x32, 0x39, 0x40, 0x47, 0x4e, 0x55, 0x5c, 0x63, 0x6a };
      if (memcmp(m.session_id, exp, 16) != 0) PONG_GOLDEN_FAIL("RESUME", "sessionId"); }
    if (m.last_tick_seen != (uint32_t)3816724390) PONG_GOLDEN_FAIL("RESUME", "lastTickSeen");
    { uint8_t back[28];
      size_t n = pong_write_resume(back, sizeof back, 10967, &m);
      if (n != sizeof back) PONG_GOLDEN_FAIL("RESUME", "<encode size>");
      if (memcmp(back, GOLDEN_RESUME, sizeof back) != 0) PONG_GOLDEN_FAIL("RESUME", "<encode bytes>"); }
    return 0;
}

static int pong_golden_check_all(void) {
    int rc = 0;
    rc |= pong_golden_check_hello();
    rc |= pong_golden_check_welcome();
    rc |= pong_golden_check_join();
    rc |= pong_golden_check_match_start();
    rc |= pong_golden_check_input();
    rc |= pong_golden_check_snapshot();
    rc |= pong_golden_check_event();
    rc |= pong_golden_check_ping();
    rc |= pong_golden_check_pong();
    rc |= pong_golden_check_bye();
    rc |= pong_golden_check_leave();
    rc |= pong_golden_check_resume();
    return rc;
}

#define PONG_GOLDEN_COUNT 12

#endif /* PONG_GOLDEN_DATA_H */
