/**
 * Emits 3ds/test/sim_trace.h: a recorded run of the TypeScript simulation that
 * the C port must reproduce exactly.
 *
 * The C simulation in src/sim/pong_sim.c exists so a local match plays by the
 * same rules as an online one. "Same rules" is a claim, and this is what makes
 * it checkable: every tick's inputs are recorded alongside the full state the
 * TypeScript produced, and 3ds/test/test_sim.c replays them.
 *
 * The INPUTS are recorded rather than regenerated in C on purpose. Generating
 * them on both sides would mean writing the generator twice, and a divergence
 * in the generator would look exactly like a divergence in the simulation --
 * the test would fail for the wrong reason and send someone hunting through the
 * physics. Replaying recorded inputs means a failure can only be the thing
 * under test.
 *
 *   npx tsx tools/gen-sim-trace.ts
 */

import { writeFileSync } from 'node:fs';
import { createMatch, stepMatch, type MatchState } from '../server/src/sim/pong.js';
import { C } from '../shared/gen/protocol.js';

const TICKS = 6000;
const SEED = 0x1234_5678;

/*
 * Three, not the real seven.
 *
 * win_score is a parameter of the simulation, so a short match exercises the
 * same ending code as a long one -- and a trace long enough to reach seven ran
 * past twelve thousand ticks, which is a 700KB generated header compiled into
 * every host test run. The value being tested is the branch, not the number.
 */
const WIN_SCORE = 3;

/**
 * Scripted inputs: each paddle chases the ball with its own periodic error.
 *
 * The periods are coprime with each other and with nothing else in the
 * simulation, so the two paddles drift in and out of phase and the run covers
 * long rallies, edge hits, wall bounces and eventually missed balls. A perfect
 * tracker would rally forever and never exercise scoring at all.
 */
function targets(tick: number, st: MatchState): [number, number] {
  /*
   * The tracking error is modulated rather than constant.
   *
   * A constant small error rallies forever and never scores; a constant large
   * one misses almost every ball and barely touches the bounce code. Both were
   * tried and both were rejected by the guards below. Sweeping the amplitude
   * through a slow cycle gives long rallies AND eventual misses in the same
   * run, which is what covers the paddle angles, the wall bounces and the
   * scoring together.
   */
  const amp = 6 + (Math.floor(tick / 240) % 5) * 6;
  const l = st.ballYQ4 + ((tick % 97) - 48) * amp;
  const r = st.ballYQ4 + ((tick % 89) - 44) * (amp + 2);
  return [l, r];
}

interface Row {
  tl: number; tr: number;
  tick: number; state: number;
  bx: number; by: number; vx: number; vy: number;
  ly: number; ry: number;
  sl: number; sr: number;
  rng: number; hits: number;
}

const st = createMatch(SEED, WIN_SCORE, C.BALL_SPEED_MAX_Q4);
const rows: Row[] = [];

for (let i = 0; i < TICKS; i++) {
  const [tl, tr] = targets(i, st);
  stepMatch(st, { targetYQ4: tl, buttons: 0 }, { targetYQ4: tr, buttons: 0 });
  rows.push({
    tl, tr,
    tick: st.tick, state: st.state,
    bx: st.ballXQ4, by: st.ballYQ4, vx: st.ballVXQ4, vy: st.ballVYQ4,
    ly: st.leftYQ4, ry: st.rightYQ4,
    sl: st.scoreL, sr: st.scoreR,
    rng: st.rng >>> 0, hits: st.rallyHits,
  });
}

/* A trace that never scored, or never finished a match, would pass while
 * testing almost nothing. Fail loudly at generation time instead. */
const goals = rows[rows.length - 1]!.sl + rows[rows.length - 1]!.sr;
const gameOver = rows.some((r) => r.state === 4);
const bounces = rows.filter((r, i) => i > 0 && r.hits > rows[i - 1]!.hits).length;
if (goals < WIN_SCORE) throw new Error(`trace scored only ${goals} goals; it is not exercising scoring`);
if (!gameOver) throw new Error('trace never reached GAME_OVER; raise TICKS');
if (bounces < 12) throw new Error(`trace has only ${bounces} paddle bounces; check the input script`);
/*
 * Both sides must score. Scoring is two separate branches -- the ball leaving
 * past x<0 and past x>FIELD_W -- and the first trace that satisfied every other
 * guard finished 0-3, exercising exactly one of them. A port could have had the
 * other branch backwards and still passed.
 */
if (rows[rows.length - 1]!.sl === 0 || rows[rows.length - 1]!.sr === 0) {
  throw new Error(
    `trace finished ${rows[rows.length - 1]!.sl}-${rows[rows.length - 1]!.sr}; ` +
    'only one goal direction is covered',
  );
}

const out: string[] = [];
out.push('/* GENERATED BY tools/gen-sim-trace.ts -- DO NOT EDIT. */');
out.push('/*');
out.push(' * A recorded run of the TypeScript simulation, replayed by test_sim.c to');
out.push(' * prove the C port agrees with it tick for tick.');
out.push(' *');
out.push(` * ${TICKS} ticks, seed 0x${SEED.toString(16)}, ending ${rows[rows.length - 1]!.sl}-${rows[rows.length - 1]!.sr}.`);
out.push(' */');
out.push('#ifndef PONG_SIM_TRACE_H');
out.push('#define PONG_SIM_TRACE_H');
out.push('#include <stdint.h>');
out.push('');
out.push(`#define PONG_SIM_TRACE_SEED 0x${SEED.toString(16)}u`);
out.push(`#define PONG_SIM_TRACE_TICKS ${TICKS}`);
out.push(`#define PONG_SIM_TRACE_WIN_SCORE ${WIN_SCORE}`);
out.push('');
out.push('typedef struct {');
out.push('    int32_t  target_l, target_r;   /* the inputs fed to this tick */');
out.push('    uint32_t tick;');
out.push('    uint8_t  state;');
out.push('    int32_t  ball_x, ball_y, ball_vx, ball_vy;');
out.push('    int32_t  left_y, right_y;');
out.push('    uint8_t  score_l, score_r;');
out.push('    uint32_t rng;');
out.push('    uint32_t rally_hits;');
out.push('} PongSimTraceRow;');
out.push('');
out.push('static const PongSimTraceRow PONG_SIM_TRACE[PONG_SIM_TRACE_TICKS] = {');
for (const r of rows) {
  out.push(
    `    {${r.tl},${r.tr},${r.tick},${r.state},${r.bx},${r.by},${r.vx},${r.vy},` +
    `${r.ly},${r.ry},${r.sl},${r.sr},${r.rng}u,${r.hits}},`,
  );
}
out.push('};');
out.push('');
out.push('#endif /* PONG_SIM_TRACE_H */');

writeFileSync('3ds/test/sim_trace.h', out.join('\n') + '\n');
console.log(
  `wrote 3ds/test/sim_trace.h: ${TICKS} ticks, final ${rows[rows.length - 1]!.sl}-${rows[rows.length - 1]!.sr}, ` +
  `${rows.filter((r) => r.state === 3).length} freeze ticks, ` +
  `${rows.filter((r, i) => i > 0 && r.hits > rows[i - 1]!.hits).length} paddle hits`,
);
